server:
  port: 8084

spring:
  application:
    name: JournalService
  datasource:
    url: jdbc:mysql://localhost:3306/apica_test_db?createDatabaseIfNotExist=true
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.subhankar.journalservice.config.JournalDTODeSerializer
      auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
