server:
  port: 8083

spring:
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/apica_test_db?createDatabaseIfNotExist=true
    username: root
    password: root@2312
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.subhankar.userservice.config.JournalDTOSerializer

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
